version: "3.3"
services:
  db:
    image: alexlapshev/anna_test_db:1.0
    container_name: anna_test_db
    restart: always
    environment:
      POSTGRES_DB: anna_test_db
      POSTGRES_USER: anna_test_user
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    image: alexlapshev/anna_test_app:1.0
    container_name: anna_test_app
    restart: always
    environment:
      SENDER_EMAIL:
      SENDER_PASSWORD: 
      DEBUG: 'False'
    ports:
      - 1984:1984
    command: bash -c "python -m api.main"
    depends_on:
      - db
volumes:
  pgdata:
